def on_button_pressed_a():
    cuteBot.move_time(cuteBot.Direction.FORWARD, 50, 1)
    basic.pause(100)
    cuteBot.motors(75, -75)
    basic.pause(100)
    cuteBot.move_time(cuteBot.Direction.FORWARD, 50, 1)
    basic.pause(100)
    cuteBot.motors(15, -15)
    basic.pause(100)
    cuteBot.move_time(cuteBot.Direction.FORWARD, 50, 1)
    basic.pause(100)
    cuteBot.motors(-90, 90)
    basic.pause(100)
    cuteBot.move_time(cuteBot.Direction.FORWARD, 50, 1)
    basic.pause(100)
    for index in range(2):
        cuteBot.motors(-145, 145)
        basic.pause(100)
        cuteBot.move_time(cuteBot.Direction.FORWARD, 50, 1)
        basic.pause(100)
        cuteBot.motors(55, -55)
        basic.pause(100)
        cuteBot.move_time(cuteBot.Direction.FORWARD, 50, 1)
        basic.pause(100)
    basic.pause(100)
    for index2 in range(2):
        cuteBot.move_time(cuteBot.Direction.FORWARD, 50, 1)
        basic.pause(100)
        cuteBot.move_time(cuteBot.Direction.BACKWARD, 50, 1)
        basic.pause(100)
    basic.pause(100)
    cuteBot.motors(100, -100)
    basic.pause(5000)
    cuteBot.stopcar()
    music._play_default_background(music.built_in_playable_melody(Melodies.FUNERAL),
        music.PlaybackMode.IN_BACKGROUND)
    strip.show_color(neopixel.colors(NeoPixelColors.INDIGO))
    strip.clear()
input.on_button_pressed(Button.A, on_button_pressed_a)

strip: neopixel.Strip = None
strip = neopixel.create(DigitalPin.P15, 2, NeoPixelMode.RGB)